
### Cria um livro
POST http://localhost:3000/books
Content-Type: application/json

{
  "name": "As Cronicas de Narnia",
  "quantity": 10,
  "author": "Alaiane Rocha Silva",
  "gender": "Fantasia",
  "ISBN": "12345678911"
}


### Buscar livro pelo ISBN ou Nome
GET http://localhost:3000/books/ISBNOrName?value=12345678911
Content-Type: application/json

