

### Criar usuário
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Alaiane",
  "CPF": "042.969.960-37",
  "address": "Rua Teste, 123",
  "phone": "51983198425",
  "email": "alaiane.rocha.silva@outlook.com"
}


### Buscar usuário pelo CPF
GET http://localhost:3000/users/cpf/042.969.960-37
Content-Type: application/json

